name: xxl-job-test
on:
  push:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Building
        run: |
          cd ./xxl-job-executor
          go build -o xxl-job-executor
